## === VANESSA ===

[vanessa]
network = "furiosa"
tailscale = "100.112.94.38"
keys = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID/AjBtg8D4lMoBkp2L3dDb5EmkOGr1v/Ns1wwRoKds4"]
age = "age1wes6w27jntng7t0fl2scuz8l0s556e4m3x3q8qfczgah90kyfs3shuqvvl"

[vanessa.ipv4]
address = "192.168.188.182"

[vanessa.users.luxus]
keys = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID/AjBtg8D4lMoBkp2L3dDb5EmkOGr1v/Ns1wwRoKds4"]
age = "age1up0p4xs0lze04acxrlxqj374ymu0dfkmc6adz2psmlz8g57ddv2qvf6pd4"


## === EMILY ===

[emily]
network = "furiosa"
tailscale = "100.71.240.35"
keys = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID/AjBtg8D4lMoBkp2L3dDb5EmkOGr1v/Ns1wwRoKds4"]
age = "age1saydygdkg49p6g34ylds3m666x0nsr2f8clwcggsn9essqdkfqjsq9a25w"

[emily.ipv4]
address = "192.168.1.174"

[emily.users.luxus]
keys = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID/AjBtg8D4lMoBkp2L3dDb5EmkOGr1v/Ns1wwRoKds4"]
## === SYNOXYN ===

[synoxyn]
network = "home"
# FIXME
# tailscale = ""

[synoxyn.ipv4]
address = "192.168.1.197"


## === KaiPhone ===

# note: on aerattum, an iphone, "users" are "apps"

[kaiphone]
network = "furiosa"

[kaiphone.users.blink]
keys = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID/AjBtg8D4lMoBkp2L3dDb5EmkOGr1v/Ns1wwRoKds4"]

[kaiphone.users.workingcopy]
keys = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID/AjBtg8D4lMoBkp2L3dDb5EmkOGr1v/Ns1wwRoKds4"]


## === KaiPad ===

[kaipad.users.blink]
keys = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID/AjBtg8D4lMoBkp2L3dDb5EmkOGr1v/Ns1wwRoKds4"]


## === INSTALLER: GRAPHICAL ===

[bootstrap-graphical]
network = "seadome"
